apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: flux-system
spec:
  containers:
  - image: amazon/aws-cli
    name: get-token
    imagePullPolicy: IfNotPresent
    envFrom:
    - secretRef:
        name: aws-credentials
    env:
    - name: REGION
      value: us-east-1 # change this if ECR repo is in a different region
    volumeMounts:
    - mountPath: /token
      name: token
        #  - image: bitnami/kubectl
        #   name: create-secret
        #imagePullPolicy: IfNotPresent
        #env:
        #    - name: SECRET_NAME
        #      value: ecr-credentials
        #    - name: ECR_REGISTRY
        #      value: <account id>.dkr.ecr.<region>.amazonaws.com # fill in the account id and region
        #    volumeMounts:
        #    - mountPath: /token
        #      name: token
        #    command:
        #    - /bin/bash
        #    - -ce
        #    - |-
        #      kubectl create secret docker-registry $SECRET_NAME \
        #        --dry-run=client \
        #        --docker-server="$ECR_REGISTRY" \
        #        --docker-username=AWS \
        #        --docker-password="$(</token/ecr-token)" \
        #        -o yaml | kubectl apply -f -              
